server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.order_updates: true
      hibernate.order_inserts: true
      hibernate.jdbc.batch_size: 10
      hibernate.connection.handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:${DATABASE_TYPE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false&autoReconnect=true&maxReconnects=10&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    ddl-auto: none

app:
  jwt:
    jwtSecret: 9dde7e6aa89563f6bbccd90f843c8a8c94fc9d55be36aba2c59509834a6ba55d877b4f0a2911da72ca0477df429a92313554d0d8fe2c6c9511dd438f22912a37
    jwtExpirationInSec: 900
    jwtRefreshSecret: 723d7a262f34adcc76a35a278ace5ea7993b0d0b42f258804c1717d80ee5c56ab59fffa2205c1db19b8092017cffb55f4074bb96505e1f231185e09dca531c48
    jwtRefreshExpirationInSec: 1200